package lox;

enum TokenType {
  NUMBER, STRING,
  LEFT_PAREN, RIGHT_PAREN,
  LEFT_BRACKET, RIGHT_BRACKET,
  COMMA, PLUS, GREATER, GREATER_EQUAL,
  LESS, LESS_EQUAL,
  SEMICOLON,
  IDENTIFIER, EQUAL, EQUAL_EQUAL,
  TRUE, FALSE, NIL,
  DAM, FLOW, IF, ELSE,
  EOF
}
