package lox;

enum TokenType {
  NUMBER, STRING,
  LEFT_PAREN, RIGHT_PAREN,
  LEFT_BRACKET, RIGHT_BRACKET,
  COMMA, PLUS, GREATER, SEMICOLON,
  IDENTIFIER, EQUAL,
  TRUE, FALSE, NIL,
  DAM, FLOW, IF, ELSE,
  EOF
}
